/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.mysql.jdbc.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author kali
 */
public class Article extends javax.swing.JFrame {
    private TableRowSorter<DefaultTableModel> rowSorter;

    /**
     * Creates new form Article
     */
    public Article() {
        initComponents();
        
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        rowSorter = new TableRowSorter<>(tblModel);
        jTable1.setRowSorter(rowSorter);
        try {
                Connection con = (Connection) db.mycon();
                String query = "SELECT * FROM Article";
                try (PreparedStatement preparedStatement = con.prepareStatement(query);
                ResultSet resultSet = preparedStatement.executeQuery()) {

                // Clear existing data in the JTable
                tblModel.setRowCount(0);

                // Populate JTable with data from the database
                while (resultSet.next()) {
                    Object[] rowData = {
                            resultSet.getString("article"),
                            resultSet.getString("prix"),
                            //Add more columns as needed
                    };
                    tblModel.addRow(rowData);
                } }
        } catch (SQLException e) {
            e.printStackTrace();
        }
      
    
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprix = new javax.swing.JTextField();
        jarticle = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();
        jadd = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jsave = new javax.swing.JButton();
        jtxtserch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprixActionPerformed(evt);
            }
        });
        getContentPane().add(jprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 140, 30));

        jarticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarticleActionPerformed(evt);
            }
        });
        getContentPane().add(jarticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 140, 30));

        jdelete.setText("Delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jadd.setText("Add");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });
        getContentPane().add(jadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });
        getContentPane().add(jupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Article_Name", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Article_Name");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Prix");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 540, 110));

        jsave.setText("Save");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jtxtserch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtserchKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtserch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 100, -1));

        jButton1.setText("Searche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprixActionPerformed

    private void jarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jarticleActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
       DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

    int selectedRowIndex = jTable1.getSelectedRow();

    if (selectedRowIndex != -1) {
        String Article, Prix;

        try {
            Connection con = (Connection) db.mycon();
            Article = tblModel.getValueAt(selectedRowIndex, 0).toString();
            Prix = tblModel.getValueAt(selectedRowIndex, 1).toString();

            String query = "DELETE FROM Article WHERE article = ? AND prix = ?";
            try (PreparedStatement prepstm = con.prepareStatement(query)) {
                prepstm.setString(1, Article);
                prepstm.setString(2, Prix);
                prepstm.executeUpdate();
            }

            tblModel.removeRow(selectedRowIndex);
            JOptionPane.showMessageDialog(this, "Data deleted successfully...");

        } catch (Exception e) {
            System.out.println(e);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row for deletion.");
    }
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{jarticle.getText(),jprix.getText()});
    }//GEN-LAST:event_jaddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
       
       String tblArticle = tblModel.getValueAt(jTable1.getSelectedRow(),0).toString();
       String tblPrix = tblModel.getValueAt(jTable1.getSelectedRow(),1).toString();
       jarticle.setText(tblArticle);
       jprix.setText(tblPrix);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
      DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
      if(jTable1.getSelectedRowCount() == 1){
          String name = jarticle.getText();
          String prix = jprix.getText();
          
          tblModel.setValueAt(name, jTable1.getSelectedRow(), 0);
          tblModel.setValueAt(name, jTable1.getSelectedRow(), 1);
          
          JOptionPane.showMessageDialog(this, "Update Successfully...");
         
      }else{
          if (jTable1.getRowCount()==0){
              JOptionPane.showMessageDialog(this, "Table is Empty..");
              
          }else{
              JOptionPane.showMessageDialog(this, "Please select Single Row For Update..");
          }
      }
    }//GEN-LAST:event_jupdateActionPerformed

    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if(tblModel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
           
        }else{
            String Article,Prix;
            try {
                Connection con = (Connection) db.mycon();
                for (int i=0;i<tblModel.getRowCount();i++){
                    Article = tblModel.getValueAt(i, 0).toString();
                    Prix = tblModel.getValueAt(i, 0).toString();
                    String query = "insert into Article(article,prix) values (?,?)";
                    PreparedStatement prepstm = con.prepareStatement(query);
                    prepstm.setString(1, Article);
                    prepstm.setString(2, Prix);
                    prepstm.execute();
                
                }
                JOptionPane.showMessageDialog(this, "Data insert succssfully...");
               
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_jsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     rowSorter.setRowFilter(RowFilter.regexFilter(jtxtserch.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtserchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtserchKeyReleased
     rowSorter.setRowFilter(RowFilter.regexFilter(jtxtserch.getText()));
    }//GEN-LAST:event_jtxtserchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jadd;
    private javax.swing.JTextField jarticle;
    private javax.swing.JButton jdelete;
    private javax.swing.JTextField jprix;
    private javax.swing.JButton jsave;
    private javax.swing.JTextField jtxtserch;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
