/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author kali
 */
public class changepass extends javax.swing.JFrame {
    PreparedStatement pst = null;
    Connection con = null;

    /**
     * Creates new form changepass
     */
    public changepass() {
        initComponents();
        con = db.mycon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jusername = new javax.swing.JTextField();
        jpass = new javax.swing.JTextField();
        jnewpass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jconfirme = new javax.swing.JButton();
        januller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("GentiumAlt", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 180, 40));

        jLabel3.setFont(new java.awt.Font("GentiumAlt", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Change password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, -1));

        jLabel4.setFont(new java.awt.Font("GentiumAlt", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please enter your ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 260, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jusername.setForeground(new java.awt.Color(51, 51, 51));
        jusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });
        jPanel1.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 340, 40));

        jpass.setForeground(new java.awt.Color(51, 51, 51));
        jpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });
        jPanel1.add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 340, 40));

        jnewpass.setForeground(new java.awt.Color(51, 51, 51));
        jnewpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 340, 40));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("UserName : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("New Password : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Password : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jconfirme.setText("Confirme");
        jconfirme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jconfirmeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jconfirmeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jconfirmeMouseExited(evt);
            }
        });
        jPanel1.add(jconfirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 110, 30));

        januller.setText("Anuller");
        januller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                janullerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                janullerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                janullerMouseExited(evt);
            }
        });
        januller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janullerActionPerformed(evt);
            }
        });
        jPanel1.add(januller, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconfirmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfirmeMouseClicked
    String username = jusername.getText();
    String pass = jpass.getText();
    String newpass = jnewpass.getText();
    
    if (username.trim().isEmpty() || pass.trim().isEmpty() || newpass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Please fill in all fields");
    } else {
        try {
            String sql = "SELECT * FROM User WHERE User_Name=? AND Password=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, pass);
            
            ResultSet resultSet = pst.executeQuery();

            if (resultSet.next()) {
                // User found, update the password
                sql = "UPDATE User SET Password=? WHERE User_Name=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, newpass);
                pst.setString(2, username);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Password updated successfully!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error connecting to the database");
        }
    }
                
    }//GEN-LAST:event_jconfirmeMouseClicked

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassActionPerformed

    private void jconfirmeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfirmeMouseEntered
        jconfirme.setBackground(Color.green);
    }//GEN-LAST:event_jconfirmeMouseEntered

    private void jconfirmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfirmeMouseExited
        jconfirme.setBackground(Color.white);
    }//GEN-LAST:event_jconfirmeMouseExited

    private void janullerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janullerMouseEntered
        januller.setBackground(Color.red);
    }//GEN-LAST:event_janullerMouseEntered

    private void janullerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janullerMouseExited
        januller.setBackground(Color.white);
    }//GEN-LAST:event_janullerMouseExited

    private void janullerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janullerMouseClicked
        
    }//GEN-LAST:event_janullerMouseClicked

    private void janullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janullerActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_janullerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton januller;
    private javax.swing.JButton jconfirme;
    private javax.swing.JTextField jnewpass;
    private javax.swing.JTextField jpass;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
